const { prisma } = require('../../lib/prisma'); const { AppError } = require('../../utils/AppError'); const { parseId, listOptions, listData } = require('../_shared/common'); const { publicUserSelect, propertySelect } = require('../_shared/selects'); const { createNotification } = require('../_shared/notifications');
function ensureAdmin(user) { if (user.role !== 'ADMIN') throw new AppError('Chỉ admin có thể thực hiện thao tác này', 403); }
async function dashboard(user) { ensureAdmin(user); const [users, rooms, properties, pendingVerifications, pendingReports, activeContracts, unpaidInvoices, recentUsers, recentReports] = await prisma.$transaction([prisma.user.count(), prisma.room.count(), prisma.property.count(), prisma.verificationRequest.count({ where: { status: 'PENDING' } }), prisma.report.count({ where: { status: { in: ['PENDING', 'PROCESSING'] } } }), prisma.contract.count({ where: { status: 'ACTIVE' } }), prisma.invoice.count({ where: { status: { in: ['UNPAID', 'OVERDUE'] } } }), prisma.user.findMany({ select: publicUserSelect, orderBy: { createdAt: 'desc' }, take: 5 }), prisma.report.findMany({ select: { id: true, targetType: true, reason: true, status: true, createdAt: true, reporter: { select: publicUserSelect } }, orderBy: { createdAt: 'desc' }, take: 5 })]); return { counts: { users, rooms, properties, pendingVerifications, pendingReports, activeContracts, unpaidInvoices }, recentUsers, recentReports }; }
async function listUsers(user, query) { ensureAdmin(user); const pagination = listOptions(query); const where = { ...(query.role ? { role: query.role } : {}), ...(query.status ? { status: query.status } : {}), ...(query.q ? { OR: [{ username: { contains: query.q } }, { fullName: { contains: query.q } }, { email: { contains: query.q } }, { phone: { contains: query.q } }] } : {}) }; const [items, total] = await prisma.$transaction([prisma.user.findMany({ where, select: { id: true, username: true, email: true, fullName: true, phone: true, avatarUrl: true, role: true, status: true, verificationStatus: true, createdAt: true, studentProfile: { select: { studentCode: true, university: { select: { id: true, name: true } } } }, landlordProfile: { select: { businessName: true } } }, orderBy: { createdAt: 'desc' }, skip: pagination.skip, take: pagination.limit }), prisma.user.count({ where })]); return listData(items, pagination, total); }
async function setUserStatus(user, value, input) { ensureAdmin(user); const id = parseId(value, 'userId'); if (id === user.id && input.status === 'DISABLED') throw new AppError('Không thể tự khóa tài khoản admin đang sử dụng', 422); const target = await prisma.user.findUnique({ where: { id }, select: { id: true, role: true } }); if (!target) throw new AppError('Không tìm thấy người dùng', 404); return prisma.user.update({ where: { id }, data: { status: input.status }, select: { id: true, username: true, fullName: true, email: true, role: true, status: true } }); }
async function setRoomStatus(user, value, input) { ensureAdmin(user); const id = parseId(value, 'roomId'); const room = await prisma.room.findUnique({ where: { id }, select: { id: true } }); if (!room) throw new AppError('Không tìm thấy phòng', 404); return prisma.room.update({ where: { id }, data: { status: input.status, ...(input.status !== 'HIDDEN' ? { publishedAt: new Date() } : {}) }, select: { id: true, name: true, status: true } }); }
async function setPropertyVerification(user, value, input) {
  ensureAdmin(user);
  const id = parseId(value, 'propertyId');
  if (!['VERIFIED', 'REJECTED'].includes(input?.status)) throw new AppError('Trạng thái xác minh khu trọ không hợp lệ', 422);
  const property = await prisma.property.findUnique({ where: { id }, select: { id: true, name: true, landlordId: true, verificationStatus: true } });
  if (!property) throw new AppError('Không tìm thấy khu trọ', 404);
  if (!['UNVERIFIED', 'PENDING'].includes(property.verificationStatus)) throw new AppError('Khu trọ này đã được xử lý xác minh', 409);
  const transition = await prisma.property.updateMany({ where: { id, verificationStatus: { in: ['UNVERIFIED', 'PENDING'] } }, data: { verificationStatus: input.status } });
  if (!transition.count) throw new AppError('Khu trọ này vừa được một quản trị viên khác xử lý', 409);
  const updated = await prisma.property.findUnique({ where: { id }, select: propertySelect });
  await createNotification(property.landlordId, { type: 'VERIFICATION', title: input.status === 'VERIFIED' ? 'Khu trọ đã được xác minh' : 'Khu trọ chưa được duyệt', content: input.status === 'VERIFIED' ? `Khu trọ ${property.name} của bạn đã được quản trị viên xác minh.` : `Khu trọ ${property.name} chưa được duyệt. Bạn có thể kiểm tra lại thông tin và liên hệ quản trị viên khi cần.`, linkUrl: '/landlord/properties' });
  return updated;
}
module.exports = { dashboard, listUsers, setUserStatus, setRoomStatus, setPropertyVerification };
