const { prisma } = require('../../lib/prisma'); const { AppError } = require('../../utils/AppError'); const { parseId, listOptions, listData } = require('../_shared/common'); const { publicUserSelect } = require('../_shared/selects'); const { createNotification } = require('../_shared/notifications');
const appointmentInclude = { room: { select: { id: true, name: true, code: true, property: { select: { id: true, name: true, address: true } } } }, student: { select: publicUserSelect }, landlord: { select: publicUserSelect } };
async function create(user, input) {
  if (user.role !== 'STUDENT') throw new AppError('Chỉ sinh viên có thể đặt lịch xem phòng', 403); if (input.scheduledAt <= new Date()) throw new AppError('Lịch xem phải ở tương lai', 422);
  const room = await prisma.room.findUnique({ where: { id: input.roomId }, select: { id: true, status: true, property: { select: { landlordId: true } } } }); if (!room || room.status === 'HIDDEN') throw new AppError('Không tìm thấy phòng', 404);
  const duplicate = await prisma.viewingAppointment.findFirst({ where: { roomId: room.id, studentId: user.id, scheduledAt: input.scheduledAt, status: { in: ['PENDING', 'ACCEPTED', 'RESCHEDULED'] } }, select: { id: true } }); if (duplicate) throw new AppError('Bạn đã có lịch xem phòng tại thời điểm này', 409);
  const appointment = await prisma.viewingAppointment.create({ data: { ...input, studentId: user.id, landlordId: room.property.landlordId }, include: appointmentInclude });
  await createNotification(room.property.landlordId, { type: 'APPOINTMENT', title: 'Có lịch xem phòng mới', content: `${user.fullName} đã đặt lịch xem phòng.`, linkUrl: '/appointments' }); return appointment;
}
async function list(user, query) {
  const pagination = listOptions(query); const roleWhere = user.role === 'STUDENT' ? { studentId: user.id } : user.role === 'LANDLORD' ? { landlordId: user.id } : {}; const where = { ...roleWhere, ...(query.status ? { status: query.status } : {}) };
  const [items, total] = await prisma.$transaction([prisma.viewingAppointment.findMany({ where, include: appointmentInclude, orderBy: { scheduledAt: 'asc' }, skip: pagination.skip, take: pagination.limit }), prisma.viewingAppointment.count({ where })]); return listData(items, pagination, total);
}
async function getForUser(user, value) { const appointment = await prisma.viewingAppointment.findUnique({ where: { id: parseId(value, 'appointmentId') }, include: appointmentInclude }); if (!appointment) throw new AppError('Không tìm thấy lịch xem', 404); if (user.role !== 'ADMIN' && appointment.studentId !== user.id && appointment.landlordId !== user.id) throw new AppError('Bạn không có quyền xem lịch này', 403); return appointment; }
async function respond(user, value, input) {
  if (user.role !== 'LANDLORD' && user.role !== 'ADMIN') throw new AppError('Chỉ chủ trọ có thể phản hồi lịch xem', 403); const appointment = await getForUser(user, value); if (user.role !== 'ADMIN' && appointment.landlordId !== user.id) throw new AppError('Bạn không quản lý lịch xem này', 403); if (!['PENDING', 'ACCEPTED', 'RESCHEDULED'].includes(appointment.status)) throw new AppError('Lịch xem này không thể cập nhật', 409); if (input.proposedAt && input.proposedAt <= new Date()) throw new AppError('Thời gian đề xuất phải ở tương lai', 422);
  const updated = await prisma.viewingAppointment.update({ where: { id: appointment.id }, data: { status: input.status, proposedAt: input.status === 'RESCHEDULED' ? input.proposedAt : null, landlordNote: input.landlordNote ?? appointment.landlordNote, respondedAt: new Date() }, include: appointmentInclude });
  await createNotification(appointment.studentId, { type: 'APPOINTMENT', title: 'Lịch xem phòng đã được phản hồi', content: `Lịch xem phòng của bạn đã được ${input.status === 'ACCEPTED' ? 'chấp nhận' : input.status === 'REJECTED' ? 'từ chối' : input.status === 'RESCHEDULED' ? 'đề xuất thời gian mới' : 'cập nhật'}.`, linkUrl: '/appointments' }); return updated;
}
async function cancel(user, value) { const appointment = await getForUser(user, value); if (user.role !== 'STUDENT' || appointment.studentId !== user.id) throw new AppError('Chỉ sinh viên đặt lịch mới có thể hủy', 403); if (!['PENDING', 'ACCEPTED', 'RESCHEDULED'].includes(appointment.status)) throw new AppError('Lịch xem này không thể hủy', 409); const updated = await prisma.viewingAppointment.update({ where: { id: appointment.id }, data: { status: 'CANCELLED', cancelledAt: new Date() }, include: appointmentInclude }); await createNotification(appointment.landlordId, { type: 'APPOINTMENT', title: 'Lịch xem phòng đã bị hủy', content: `${user.fullName} đã hủy lịch xem phòng.`, linkUrl: '/appointments' }); return updated; }
module.exports = { create, list, getForUser, respond, cancel };
