const { asyncHandler } = require('../../utils/asyncHandler');
const { success, created } = require('../../utils/response');
const service = require('./service');
const create = asyncHandler(async (req, res) => created(res, { message: 'Đã gửi lời mời ở ghép', data: await service.send(req.user, req.body) }));
const sent = asyncHandler(async (req, res) => success(res, await service.list(req.user, 'sent', req.query)));
const received = asyncHandler(async (req, res) => success(res, await service.list(req.user, 'received', req.query)));
const list = asyncHandler(async (req, res) => success(res, await service.listAll(req.user, req.query)));
const respond = asyncHandler(async (req, res) => success(res, { message: 'Đã xử lý lời mời ở ghép', data: await service.act(req.user, req.params.id, req.body.action) }));
const update = respond;
module.exports = { create, sent, received, list, respond, update };
