const crypto = require('crypto'); const { prisma } = require('../../lib/prisma'); const { AppError } = require('../../utils/AppError'); const { calculateInvoiceAmount } = require('../../services/calculation.service'); const { parseId, listOptions, listData } = require('../_shared/common'); const { publicUserSelect } = require('../_shared/selects'); const { createNotification } = require('../_shared/notifications');
const invoiceInclude = { contract: { select: { id: true, contractNumber: true, room: { select: { id: true, name: true, code: true, property: { select: { name: true, address: true } } } }, landlord: { select: publicUserSelect }, tenants: { include: { student: { select: publicUserSelect } } } } }, items: { orderBy: { id: 'asc' } } };
async function get(value) { const invoice = await prisma.invoice.findUnique({ where: { id: parseId(value, 'invoiceId') }, include: invoiceInclude }); if (!invoice) throw new AppError('Không tìm thấy hóa đơn', 404); return invoice; }
async function getForUser(user, value) { const invoice = await get(value); const isTenant = invoice.contract.tenants.some((tenant) => tenant.studentId === user.id); if (user.role !== 'ADMIN' && invoice.contract.landlord.id !== user.id && !isTenant) throw new AppError('Bạn không có quyền xem hóa đơn này', 403); return invoice; }
async function assertManager(user, contractId) { const contract = await prisma.contract.findUnique({ where: { id: contractId }, include: { room: { select: { id: true } }, tenants: { select: { studentId: true } } } }); if (!contract) throw new AppError('Không tìm thấy hợp đồng', 404); if (user.role !== 'ADMIN' && (user.role !== 'LANDLORD' || contract.landlordId !== user.id)) throw new AppError('Bạn không có quyền quản lý hóa đơn của hợp đồng này', 403); if (contract.status !== 'ACTIVE') throw new AppError('Chỉ hợp đồng đang hiệu lực mới có thể lập hóa đơn', 409); return contract; }
function buildItems(calculated, input) { const rows = [ ['RENT', 'Tiền phòng', 1, input.rent], ['ELECTRICITY', 'Tiền điện', calculated.electricityUsage, input.electricityUnitPrice], ['WATER', 'Tiền nước', calculated.waterUsage, input.waterUnitPrice], ['INTERNET', 'Internet', 1, input.internet], ['PARKING', 'Gửi xe', 1, input.parking], ['SERVICE', 'Dịch vụ', 1, input.service], ['OTHER', 'Khoản khác', 1, input.other] ]; return rows.filter(([, , quantity, unitPrice], index) => index < 3 || Number(unitPrice) > 0).map(([type, description, quantity, unitPrice]) => ({ type, description, quantity, unitPrice, amount: type === 'ELECTRICITY' ? calculated.electricityAmount : type === 'WATER' ? calculated.waterAmount : Number(quantity) * Number(unitPrice) })); }
async function create(user, input) {
  if (user.role !== 'LANDLORD' && user.role !== 'ADMIN') throw new AppError('Chỉ chủ trọ có thể lập hóa đơn', 403); const contract = await assertManager(user, input.contractId); const rent = input.rentAmount ?? Number(contract.rent); const values = { rent, electricityStart: input.electricityStart, electricityEnd: input.electricityEnd, electricityUnitPrice: input.electricityUnitPrice, waterStart: input.waterStart, waterEnd: input.waterEnd, waterUnitPrice: input.waterUnitPrice, internet: input.internetAmount, parking: input.parkingAmount, service: input.serviceAmount, other: input.otherAmount }; const calculated = calculateInvoiceAmount(values);
  const duplicate = await prisma.invoice.findUnique({ where: { contractId_periodStart_periodEnd: { contractId: contract.id, periodStart: input.periodStart, periodEnd: input.periodEnd } }, select: { id: true } }); if (duplicate) throw new AppError('Đã có hóa đơn cho kỳ này', 409);
  const invoiceNumber = `HD-${contract.id}-${input.periodEnd.toISOString().slice(0, 10).replace(/-/g, '')}-${crypto.randomUUID().slice(0, 6).toUpperCase()}`;
  const invoice = await prisma.invoice.create({ data: { invoiceNumber, contractId: contract.id, periodStart: input.periodStart, periodEnd: input.periodEnd, dueDate: input.dueDate, electricityStart: values.electricityStart, electricityEnd: values.electricityEnd, electricityUsage: calculated.electricityUsage, electricityUnitPrice: values.electricityUnitPrice, electricityAmount: calculated.electricityAmount, waterStart: values.waterStart, waterEnd: values.waterEnd, waterUsage: calculated.waterUsage, waterUnitPrice: values.waterUnitPrice, waterAmount: calculated.waterAmount, rentAmount: values.rent, internetAmount: values.internet, parkingAmount: values.parking, serviceAmount: values.service, otherAmount: values.other, totalAmount: calculated.total, items: { create: buildItems(calculated, values) } }, include: invoiceInclude });
  await Promise.all(contract.tenants.map((tenant) => createNotification(tenant.studentId, { type: 'INVOICE', title: 'Có hóa đơn mới', content: `Hóa đơn ${invoice.invoiceNumber} đã được tạo.`, linkUrl: `/invoices/${invoice.id}` }))); return invoice;
}
async function refreshOverdue() { await prisma.invoice.updateMany({ where: { status: 'UNPAID', dueDate: { lt: new Date() } }, data: { status: 'OVERDUE' } }); }
async function list(user, query) { await refreshOverdue(); const pagination = listOptions(query); const roleWhere = user.role === 'STUDENT' ? { contract: { is: { tenants: { some: { studentId: user.id } } } } } : user.role === 'LANDLORD' ? { contract: { is: { landlordId: user.id } } } : {}; const where = { ...roleWhere, ...(query.status ? { status: query.status } : {}) }; const [items, total] = await prisma.$transaction([prisma.invoice.findMany({ where, include: invoiceInclude, orderBy: { dueDate: 'desc' }, skip: pagination.skip, take: pagination.limit }), prisma.invoice.count({ where })]); return listData(items, pagination, total); }
async function updateStatus(user, value, input) { const invoice = await getForUser(user, value); if (user.role !== 'ADMIN' && (user.role !== 'LANDLORD' || invoice.contract.landlord.id !== user.id)) throw new AppError('Bạn không có quyền cập nhật hóa đơn này', 403); if (!['UNPAID', 'OVERDUE'].includes(invoice.status) && input.status !== 'CANCELLED') throw new AppError('Hóa đơn đã được xử lý', 409); const updated = await prisma.invoice.update({ where: { id: invoice.id }, data: { status: input.status, paidAt: input.status === 'PAID' ? new Date() : null }, include: invoiceInclude }); await Promise.all(invoice.contract.tenants.map((tenant) => createNotification(tenant.studentId, { type: 'INVOICE', title: 'Trạng thái hóa đơn đã thay đổi', content: `Hóa đơn ${invoice.invoiceNumber} đã được ${input.status === 'PAID' ? 'đánh dấu đã thanh toán' : 'hủy'}.`, linkUrl: `/invoices/${invoice.id}` }))); return updated; }
module.exports = { create, list, getForUser, updateStatus };
