const crypto = require('crypto'); const { prisma } = require('../../lib/prisma'); const { AppError } = require('../../utils/AppError'); const { parseId, listOptions, listData } = require('../_shared/common'); const { publicUserSelect } = require('../_shared/selects'); const { createNotification } = require('../_shared/notifications');
const contractInclude = { room: { select: { id: true, name: true, code: true, capacity: true, availableSlots: true, property: { select: { id: true, name: true, address: true } } } }, landlord: { select: publicUserSelect }, tenants: { include: { student: { select: publicUserSelect } }, orderBy: { isPrimaryTenant: 'desc' } }, invoices: { select: { id: true, invoiceNumber: true, totalAmount: true, status: true, dueDate: true }, orderBy: { periodEnd: 'desc' } } };
async function get(value) { const contract = await prisma.contract.findUnique({ where: { id: parseId(value, 'contractId') }, include: contractInclude }); if (!contract) throw new AppError('Không tìm thấy hợp đồng', 404); return contract; }
async function getForUser(user, value) { const contract = await get(value); const tenant = contract.tenants.some((entry) => entry.studentId === user.id); if (user.role !== 'ADMIN' && contract.landlordId !== user.id && !tenant) throw new AppError('Bạn không có quyền xem hợp đồng này', 403); return contract; }
async function ensureLandlordRoom(user, roomId) { const room = await prisma.room.findUnique({ where: { id: roomId }, select: { id: true, capacity: true, availableSlots: true, status: true, property: { select: { landlordId: true } } } }); if (!room || room.status === 'HIDDEN') throw new AppError('Không tìm thấy phòng', 404); if (user.role !== 'ADMIN' && (user.role !== 'LANDLORD' || room.property.landlordId !== user.id)) throw new AppError('Bạn không quản lý phòng này', 403); return room; }
async function ensureTenants(tenants) { const ids = tenants.map((item) => item.studentId); const students = await prisma.user.findMany({ where: { id: { in: ids }, role: 'STUDENT', status: 'ACTIVE' }, select: { id: true } }); if (students.length !== ids.length) throw new AppError('Có sinh viên thuê không hợp lệ', 422); }
async function create(user, input) {
  if (user.role !== 'LANDLORD' && user.role !== 'ADMIN') throw new AppError('Chỉ chủ trọ có thể tạo hợp đồng', 403); await ensureLandlordRoom(user, input.roomId); await ensureTenants(input.tenants);
  const contractNumber = input.contractNumber || `HD-${new Date().getFullYear()}-${input.roomId}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`;
  const exists = await prisma.contract.findUnique({ where: { contractNumber }, select: { id: true } }); if (exists) throw new AppError('Số hợp đồng đã tồn tại', 409);
  const { tenants, ...data } = input; return prisma.contract.create({ data: { ...data, contractNumber, landlordId: user.role === 'ADMIN' ? (await prisma.room.findUnique({ where: { id: input.roomId }, select: { property: { select: { landlordId: true } } } })).property.landlordId : user.id, tenants: { create: tenants.map((tenant, index) => ({ ...tenant, isPrimaryTenant: tenant.isPrimaryTenant || index === 0 })) } }, include: contractInclude });
}
async function list(user, query) { const pagination = listOptions(query); const roleWhere = user.role === 'STUDENT' ? { tenants: { some: { studentId: user.id } } } : user.role === 'LANDLORD' ? { landlordId: user.id } : {}; const where = { ...roleWhere, ...(query.status ? { status: query.status } : {}) }; const [items, total] = await prisma.$transaction([prisma.contract.findMany({ where, include: contractInclude, orderBy: { createdAt: 'desc' }, skip: pagination.skip, take: pagination.limit }), prisma.contract.count({ where })]); return listData(items, pagination, total); }
async function assertManager(user, value) { const contract = await get(value); if (user.role !== 'ADMIN' && (user.role !== 'LANDLORD' || contract.landlordId !== user.id)) throw new AppError('Bạn không có quyền quản lý hợp đồng này', 403); return contract; }
async function transition(user, value, input) {
  const contract = await assertManager(user, value); if (contract.status === input.status) return contract;
  if (input.status === 'ACTIVE') {
    if (contract.status !== 'DRAFT') throw new AppError('Chỉ hợp đồng nháp mới có thể kích hoạt', 409); const activeTenants = contract.tenants.filter((tenant) => !tenant.moveOutDate).length; const room = await prisma.room.findUnique({ where: { id: contract.roomId }, select: { availableSlots: true, status: true } }); if (!room || room.status === 'HIDDEN') throw new AppError('Phòng không thể kích hoạt hợp đồng', 422); if (room.availableSlots < activeTenants) throw new AppError('Phòng không còn đủ chỗ trống cho hợp đồng', 409);
    const updated = await prisma.$transaction(async (tx) => { await tx.room.update({ where: { id: contract.roomId }, data: { availableSlots: { decrement: activeTenants }, status: room.availableSlots === activeTenants ? 'RENTED' : 'AVAILABLE' } }); return tx.contract.update({ where: { id: contract.id }, data: { status: 'ACTIVE', signedAt: new Date() }, include: contractInclude }); }); await Promise.all(contract.tenants.map((tenant) => createNotification(tenant.studentId, { type: 'CONTRACT', title: 'Hợp đồng đã được kích hoạt', content: `Hợp đồng ${contract.contractNumber} đã có hiệu lực.`, linkUrl: `/contracts/${contract.id}` }))); return updated;
  }
  if (input.status === 'TERMINATED') {
    if (contract.status !== 'ACTIVE') throw new AppError('Chỉ hợp đồng đang hiệu lực mới có thể chấm dứt', 409); const activeTenants = contract.tenants.filter((tenant) => !tenant.moveOutDate).length; const updated = await prisma.$transaction(async (tx) => { const room = await tx.room.findUnique({ where: { id: contract.roomId }, select: { capacity: true, availableSlots: true } }); await tx.room.update({ where: { id: contract.roomId }, data: { availableSlots: Math.min(room.capacity, room.availableSlots + activeTenants), status: 'AVAILABLE' } }); return tx.contract.update({ where: { id: contract.id }, data: { status: 'TERMINATED', terminatedAt: new Date() }, include: contractInclude }); }); await Promise.all(contract.tenants.map((tenant) => createNotification(tenant.studentId, { type: 'CONTRACT', title: 'Hợp đồng đã chấm dứt', content: `Hợp đồng ${contract.contractNumber} đã được chấm dứt.`, linkUrl: `/contracts/${contract.id}` }))); return updated;
  }
  if (input.status === 'EXPIRED') { if (!['ACTIVE', 'DRAFT'].includes(contract.status)) throw new AppError('Không thể chuyển trạng thái hợp đồng', 409); return prisma.contract.update({ where: { id: contract.id }, data: { status: 'EXPIRED' }, include: contractInclude }); }
  throw new AppError('Trạng thái hợp đồng không hợp lệ', 422);
}
module.exports = { create, list, getForUser, transition };
