const { prisma } = require('../../lib/prisma'); const { AppError } = require('../../utils/AppError'); const { parseId, listOptions, listData } = require('../_shared/common'); const { publicUserSelect } = require('../_shared/selects'); const { createNotification } = require('../_shared/notifications');
const verificationInclude = { user: { select: publicUserSelect }, reviewedBy: { select: publicUserSelect } };
function expectedType(role) { return role === 'STUDENT' ? 'STUDENT' : role === 'LANDLORD' ? 'LANDLORD' : null; }
async function submit(user, input) { const type = expectedType(user.role); if (!type) throw new AppError('Tài khoản admin không cần xác minh', 403); if (input.type !== type) throw new AppError('Loại xác minh không khớp vai trò tài khoản', 422); const pending = await prisma.verificationRequest.findFirst({ where: { userId: user.id, status: 'PENDING' }, select: { id: true } }); if (pending) throw new AppError('Bạn đã có yêu cầu xác minh đang chờ duyệt', 409); if (type === 'STUDENT' && !input.studentCode && !input.schoolEmail && !input.documentUrl) throw new AppError('Cần cung cấp ít nhất một thông tin xác minh sinh viên', 422); if (type === 'LANDLORD' && !input.documentUrl && !input.note) throw new AppError('Cần cung cấp tài liệu hoặc ghi chú xác minh chủ trọ', 422); return prisma.$transaction(async (tx) => { const request = await tx.verificationRequest.create({ data: { ...input, userId: user.id, status: 'PENDING' }, include: verificationInclude }); await tx.user.update({ where: { id: user.id }, data: { verificationStatus: 'PENDING' } }); return request; }); }
async function mine(user, query) { const pagination = listOptions(query); const where = { userId: user.id, ...(query.status ? { status: query.status } : {}) }; const [items, total] = await prisma.$transaction([prisma.verificationRequest.findMany({ where, include: verificationInclude, orderBy: { createdAt: 'desc' }, skip: pagination.skip, take: pagination.limit }), prisma.verificationRequest.count({ where })]); return listData(items, pagination, total); }
async function list(user, query) { if (user.role !== 'ADMIN') throw new AppError('Chỉ admin có thể xem danh sách xác minh', 403); const pagination = listOptions(query); const where = { ...(query.status ? { status: query.status } : {}), ...(query.type ? { type: query.type } : {}) }; const [items, total] = await prisma.$transaction([prisma.verificationRequest.findMany({ where, include: verificationInclude, orderBy: { createdAt: 'asc' }, skip: pagination.skip, take: pagination.limit }), prisma.verificationRequest.count({ where })]); return listData(items, pagination, total); }
async function review(user, value, input) { if (user.role !== 'ADMIN') throw new AppError('Chỉ admin có thể duyệt xác minh', 403); const request = await prisma.verificationRequest.findUnique({ where: { id: parseId(value, 'verificationId') }, include: verificationInclude }); if (!request) throw new AppError('Không tìm thấy yêu cầu xác minh', 404); if (request.status !== 'PENDING') throw new AppError('Yêu cầu xác minh này đã được xử lý', 409); if (input.status === 'VERIFIED' && request.type === 'STUDENT') { if (request.studentCode) { const owner = await prisma.studentProfile.findUnique({ where: { studentCode: request.studentCode }, select: { userId: true } }); if (owner && owner.userId !== request.userId) throw new AppError('Mã sinh viên đã được dùng bởi tài khoản khác', 409); } if (request.schoolEmail) { const owner = await prisma.studentProfile.findUnique({ where: { schoolEmail: request.schoolEmail }, select: { userId: true } }); if (owner && owner.userId !== request.userId) throw new AppError('Email trường đã được dùng bởi tài khoản khác', 409); } }
  const updated = await prisma.$transaction(async (tx) => { const result = await tx.verificationRequest.update({ where: { id: request.id }, data: { status: input.status, reviewerNote: input.reviewerNote || null, reviewedById: user.id, reviewedAt: new Date() }, include: verificationInclude }); await tx.user.update({ where: { id: request.userId }, data: { verificationStatus: input.status } }); if (input.status === 'VERIFIED' && request.type === 'STUDENT') await tx.studentProfile.upsert({ where: { userId: request.userId }, update: { ...(request.studentCode ? { studentCode: request.studentCode } : {}), ...(request.schoolEmail ? { schoolEmail: request.schoolEmail } : {}) }, create: { userId: request.userId, studentCode: request.studentCode || null, schoolEmail: request.schoolEmail || null } }); return result; }); await createNotification(request.userId, { type: 'VERIFICATION', title: 'Yêu cầu xác minh đã được xử lý', content: `Yêu cầu xác minh của bạn đã ${input.status === 'VERIFIED' ? 'được duyệt' : 'bị từ chối'}.`, linkUrl: request.type === 'LANDLORD' ? '/landlord/profile' : '/student/profile' }); return updated; }
module.exports = { submit, mine, list, review };
