const { asyncHandler } = require('../../utils/asyncHandler');
const { success, created } = require('../../utils/response');
const service = require('./service');
const list = asyncHandler(async (req, res) => success(res, await service.list(req.query, req.user)));
const show = asyncHandler(async (req, res) => success(res, { data: await service.get(req.params.id) }));
const geocode = asyncHandler(async (req, res) => success(res, { data: { items: await service.geocodeAddress(req.body.address, req.user) } }));
const create = asyncHandler(async (req, res) => created(res, { message: 'Đã tạo khu trọ', data: await service.create(req.user, req.body) }));
const update = asyncHandler(async (req, res) => success(res, { message: 'Đã cập nhật khu trọ', data: await service.update(req.user, req.params.id, req.body) }));
const remove = asyncHandler(async (req, res) => { await service.remove(req.user, req.params.id); return success(res, { message: 'Đã xóa khu trọ' }); });
const places = asyncHandler(async (req, res) => success(res, { data: { items: await service.listNearbyPlaces(req.params.id) } }));
const createPlace = asyncHandler(async (req, res) => created(res, { message: 'Đã thêm tiện ích xung quanh', data: await service.createNearbyPlace(req.user, req.params.id, req.body) }));
const removePlace = asyncHandler(async (req, res) => { await service.removeNearbyPlace(req.user, req.params.id, req.params.placeId); return success(res, { message: 'Đã xóa tiện ích xung quanh' }); });
module.exports = { list, show, geocode, create, update, remove, places, createPlace, removePlace };
