const express = require('express');
const { authenticate, authorize } = require('../../middleware/auth.middleware');
const { validate } = require('../../middleware/validate.middleware');
const controller = require('./controller');
const { listUniversitiesSchema, universitySchema, universityUpdateSchema } = require('./validator');
const router = express.Router();
router.get('/', validate(listUniversitiesSchema, 'query'), controller.list);
router.get('/:id', controller.show);
router.post('/', authenticate, authorize('ADMIN'), validate(universitySchema), controller.create);
router.patch('/:id', authenticate, authorize('ADMIN'), validate(universityUpdateSchema), controller.update);
router.delete('/:id', authenticate, authorize('ADMIN'), controller.remove);
module.exports = { universitiesRouter: router };
