const { asyncHandler } = require('../../utils/asyncHandler');
const { success, created } = require('../../utils/response');
const service = require('./service');
const list = asyncHandler(async (req, res) => success(res, await (req.query.mine ? service.mine(req.user, req.query) : service.list(req.query, req.user))));
const mine = asyncHandler(async (req, res) => success(res, await service.mine(req.user, req.query)));
const show = asyncHandler(async (req, res) => success(res, { data: await service.get(req.params.id) }));
const create = asyncHandler(async (req, res) => created(res, { message: 'Đã đăng bài tìm người ở ghép', data: await service.create(req.user, req.body) }));
const update = asyncHandler(async (req, res) => success(res, { message: 'Đã cập nhật bài đăng', data: await service.update(req.user, req.params.id, req.body) }));
const close = asyncHandler(async (req, res) => success(res, { message: 'Đã đóng bài đăng', data: await service.close(req.user, req.params.id) }));
const remove = asyncHandler(async (req, res) => success(res, { message: 'Đã lưu trữ bài đăng', data: await service.remove(req.user, req.params.id) }));
module.exports = { list, mine, show, create, update, close, remove };
